### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by sirbastiano** [Rich-Hall/sentinel1Level0DecodingDemo#3]
I have no other way to reach you and compliment you for this stunning work! A true gem!

**Comment by Rich-Hall** [comment]
Thank you!

**Comment by sirbastiano** [comment]
Dear RH, I have some questions about the code. Are you available to discuss a little bit?

**Comment by Rich-Hall** [comment]
Sure! I have sent an email to the unina.it address listed in your profile. :)

**Comment by sirbastiano** [comment]
Ciao Rich,
we are experimenting but it seems that using a hamming window reduces this
folding effect!

Rob

Il giorno gio 25 gen 2024 alle ore 05:54 Rich Hall ***@***.***>
ha scritto:
