### ISSUE TITLE
value error when decoding

### ISSUE THREAD

**Issue by JCdef** [Rich-Hall/sentinel1Level0DecodingDemo#5]
Dear Rich-Hall,

I hope this message finds you well. Firstly, I want to express my sincere appreciation for the remarkable work you've done on this project. 

I recently came across your project on GitHub and  I followed the instructions provided in the README to download the dataset. However, when I attempted to execute the code:

l0file = sentinel1decoder.Level0File(inputfile)

I encountered the following error:

ValueError: Length of new names must be 1, got 2

I have double-checked my steps against the README, but I'm still facing this issue. Could you kindly provide some guidance or insights on how to resolve this error?
![ValueError](https://github.com/Rich-Hall/sentinel1Level0DecodingDemo/assets/115679709/01075b8c-ba53-4c2d-add4-eb47018d91fc)

**Comment by JCdef** [comment]
And I continue to face the same error even after using the dataset "S1A_S3_RAW__0SDH_20220710T213600_20220710T213625_044043_0541DB_56CE" as specified in the README. Could you kindly provide some guidance or insights on how to resolve this error?

**Comment by richhall-zipline** [comment]
Hi JCdef - what version of Pandas are you using? You may need to update this package. Try calling this to see the version:

```
import pandas as pd
print(pd.__version__)
```

The required functionality here is setting index names of a dataframe via `DatafFrame.index.names = [whatever]`. You could test via something like

```
df = pd.DataFrame([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [3, 4, 5, 6, 7,],
    [3, 4, 5, 6, 7,],
    [3, 4, 5, 6, 7,],
    [6, 7, 8, 9, 0],
    [6, 7, 8, 9, 0],
    [6, 7, 8, 9, 0],
    [6, 7, 8, 9, 1],
    [6, 7, 8, 9, 1],
    [6, 7, 8, 9, 1],
])

df = df.groupby(
            df[[3, 4]]
            .diff()
            .ne(0)
            .any(axis=1)
            .cumsum(), group_keys=True
        ).apply(lambda x: x)

df.index.names = [
            'aaa',
            'bbb',
        ]
```

This works for me, but seems to be the source of your error. I note that your error stacktrace calls out the error occurring on line 1522 of `pandas.core.indexes.base`, but [the most recent version of the package has this code on line 1785 of this file](https://github.com/pandas-dev/pandas/blob/e6d0c1ac4a550bd15f4451594af41be9ae74c62c/pandas/core/indexes/base.py#L1785). This suggests to me that something is out of date. I can look into it further everything's already up to date.

**Comment by Rich-Hall** [comment]
Hi JCdef - what version of Pandas are you using? You may need to update this package. Try calling this to see the version:

```
import pandas as pd
print(pd.__version__)
```

The required functionality here is setting index names of a dataframe via DatafFrame.index.names = [whatever]. You could test via something like

```
df = pd.DataFrame([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [3, 4, 5, 6, 7,],
    [3, 4, 5, 6, 7,],
    [3, 4, 5, 6, 7,],
    [6, 7, 8, 9, 0],
    [6, 7, 8, 9, 0],
    [6, 7, 8, 9, 0],
    [6, 7, 8, 9, 1],
    [6, 7, 8, 9, 1],
    [6, 7, 8, 9, 1],
])

df = df.groupby(
            df[[3, 4]]
            .diff()
            .ne(0)
            .any(axis=1)
            .cumsum(), group_keys=True
        ).apply(lambda x: x)

df.index.names = [
            'aaa',
            'bbb',
        ]
```

This works for me, but seems to be the source of your error. I note that your error stacktrace calls out the error occurring on line 1522 of pandas.core.indexes.base, but [the most recent version of the package has this code on line 1785 of this file](https://github.com/pandas-dev/pandas/blob/e6d0c1ac4a550bd15f4451594af41be9ae74c62c/pandas/core/indexes/base.py#L1785). This suggests to me that something is out of date. I can look into it further everything's already up to date.

**Comment by JCdef** [comment]
Hi Rich-Hall, I sincerely appreciate your assistance! It works after updating Pandas. Thank you so much for your help!
