### ISSUE TITLE
Help locating the data file

### ISSUE THREAD

**Issue by sourcesync** [Rich-Hall/sentinel1Level0DecodingDemo#9]
Hi,

Can you provide an alternate download location for the file "S1A_S3_RAW__0SDH_20220710T213600_20220710T213625_044043_0541DB_56CE"?

I was not able to locate it at the Copernicus data hub.

Thanks!

**Comment by Rich-Hall** [comment]
I'm not sure if that file is still available, it's quite old now (from 2022). Some further guidance in the matching issue on the decoder package repo here - https://github.com/Rich-Hall/sentinel1decoder/issues/6#issuecomment-2484231018

**Comment by sourcesync** [comment]
Thanks @Rich-Hall for the prompt response!

I submitted a ticket to the Copernicus data hub and they responded with the download instructions.

For anyone else looking here is the command you would run:

aws s3 sync s3://eodata/Sentinel-1/SAR/RAW/2022/07/10/S1A_S3_RAW__0SDH_20220710T213600_20220710T213625_044043_0541DB_56CE.SAFE/  <local_dir>
